apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-files
  namespace: webinar
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi
